### PR TITLE
rm bootstrap

### LINKED ISSUE #344: Remove `bootstrap` dependency
Will make the upgrade to React 18 much easier and it's not really necessary - everything can be handled with pure CSS

- [ ] `Login.jsx`
- [ ] `Error.jsx`
- [ ] `camera.js` (`buildCameraStartTrial` and `buildCameraEndTrial`)

### PR DESCRIPTION
**Pull request by YUUU23**
In `Login.jsx`: 
- refactor form and button to use vanilla HTML + CSS (styling may not be exactly like bootstrap styling, but should be very similar); all new CSS added in place of the bootstrap styling is in `index.css`
- remove all related bootstrap imports (also removed in `App.jsx`)

In `Camera.js`; 
- remove centering camera bootstrap classes and added CSS to simply center those elements when setting up and ending camera

Change `alert alert-danger` to `alert-danger` CSS class with similar styling as bootstrap's alert-danger class

### CODE REVIEW

**Comment by YUUU23** [comment]
Should I remove the boostrap dependency manually from `package.json` or does it get automatically removed when rebuilding we do not use bootstrap anywhere?

**Comment by RobertGemmaJr** [comment]
> Should I remove the boostrap dependency manually from `package.json` or does it get automatically removed when rebuilding we do not use bootstrap anywhere?

You'll have to remove it manually! You can run `npm uninstall bootstrap react-bootstrap` to uninstall the dependencies

**Review by RobertGemmaJr — COMMENTED** [review]
Fantastic! Just uninstall the dependencies we no longer need and this will be good to go!

**Comment by YUUU23** [comment]
> Fantastic! Just uninstall the dependencies we no longer need and this will be good to go!

Just made this change! Would you be able to check one more time if everything looks good? 
Thanks!

**Review by RobertGemmaJr — APPROVED** [review]
Looks fantastic!

**Pull request merged**
