### PR TITLE
Ref event codes json

### LINKED ISSUE #333: Move `event_code`s to `config.json`

### PR DESCRIPTION
**Pull request by YUUU23**
- moved `eventCodes` into its own json file 
- change import/export in `trigger.js` accordingly 
- should we rename the final export in `trigger.js` `EVENT_CODES` instead of `eventCodes`? Also not entirely sure if we want to name this file `config.json` as mentioned in the issue or `eventCodes.json` 

- merged into `ref-config-env-idx` since a lot of the changes there are related to this modification; this branch was also based on `ref-config-env-idx`. This can also be changed to base on `v4` branch if needed.

### CODE REVIEW

**Comment by RobertGemmaJr** [comment]
>  This can also be changed to base on `v4` branch if needed.

This will happen automatically! When `ref-config-env-idx` gets merged into `v4` this branch's base will be updated by GitHub

**Comment by RobertGemmaJr** [comment]
Actually, @YUUU23 it looks like this branch should be going into [ref-config-as-ENV](https://github.com/brown-ccv/honeycomb/tree/ref-config-as-ENV)?

**Comment by YUUU23** [comment]
> ref-config-as-ENV

Yes! I will change this.

**Review by RobertGemmaJr — APPROVED** [review]
Awesome! I think eventually we can work on moving the `trigger` variable out but let's not worry about that right now. That will hopefully be removed completely in version 5 so we it's not worth it for us to change it right now

**Pull request merged**
